---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - solar.opendefense.cloud
  resources:
  - clusteritems/finalizers
  verbs:
  - update
- apiGroups:
  - solar.opendefense.cloud
  resources:
  - clusteritems/status
  verbs:
  - get
  - patch
  - update
