{{- if and .Values.controller.enabled .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "solar.controller.fullname" . }}
  labels:
    {{- include "solar.controller.labels" . | nindent 4 }}
rules:
  {{- $role := .Files.Get "files/role.yaml" | fromYaml }}
  {{- $role.rules | toYaml | nindent 2 }}
  {{- with .Values.rbac.additionalControllerRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
