{{- if .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solar.controller.fullname" . }}
  namespace: {{ include "solar.namespace" . }}
  labels:
    {{- include "solar.controller.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      {{- include "solar.controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "solar.controller.selectorLabels" . | nindent 8 }}
        {{- with .Values.controller.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      {{- if not $.Values.controller.imagePullSecrets }}
      imagePullSecrets:
      {{- end }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "solar.controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controller.podSecurityContext | nindent 8 }}
      containers:
        - name: manager
          image: {{ include "solar.controller.image" . }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          {{- with .Values.controller.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --health-probe-bind-address={{ .Values.controller.args.healthProbeBindAddress }}
            {{- if .Values.controller.metrics.enabled }}
            - --metrics-bind-address={{ .Values.controller.args.metricsBindAddress }}
            - --metrics-secure={{ .Values.controller.args.metricsSecure }}
            {{- if .Values.controller.metrics.certManager.enabled }}
            - --metrics-cert-path={{ .Values.controller.metrics.certManager.certPath }}
            - --metrics-cert-name={{ .Values.controller.metrics.certManager.certName }}
            - --metrics-cert-key={{ .Values.controller.metrics.certManager.certKey }}
            {{- end }}
            {{- else }}
            - --metrics-bind-address=0
            {{- end }}
            - --enable-http2={{ .Values.controller.args.enableHTTP2 }}
            {{- if .Values.controller.args.leaderElect }}
            - --leader-elect
            {{- end }}
            {{- if .Values.controller.args.pprofBindAddress }}
            - --pprof-bind-address={{ .Values.controller.args.pprofBindAddress }}
            {{- end }}
            {{- range $key, $value := .Values.controller.extraArgs }}
            - --{{ $key }}={{ $value }}
            {{- end }}
          {{- with .Values.controller.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.controller.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.controller.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
          {{- if .Values.controller.metrics.certManager.enabled }}
          volumeMounts:
            - name: metrics-certs
              mountPath: {{ .Values.controller.metrics.certManager.certPath }}
              readOnly: true
          {{- end }}
      {{- if .Values.controller.metrics.certManager.enabled }}
      volumes:
        - name: metrics-certs
          secret:
            secretName: {{ include "solar.controller.fullname" . }}-metrics-cert
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
{{- end }}
