{{- if and .Values.controller.enabled .Values.controller.metrics.enabled .Values.controller.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "solar.controller.fullname" . }}
  namespace: {{ include "solar.namespace" . }}
  labels:
    {{- include "solar.controller.labels" . | nindent 4 }}
    {{- with .Values.controller.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "solar.controller.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: https
      scheme: https
      interval: {{ .Values.controller.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.controller.metrics.serviceMonitor.scrapeTimeout }}
      tlsConfig:
        insecureSkipVerify: true
{{- end }}
