{{- if .Values.apiserver.enabled }}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.solar.opendefense.cloud
  labels:
    {{- include "solar.apiserver.labels" . | nindent 4 }}
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ include "solar.namespace" . }}/{{ include "solar.certManager.certificateName" . }}
  {{- end }}
spec:
  group: solar.opendefense.cloud
  version: v1alpha1
  service:
    namespace: {{ include "solar.namespace" . }}
    name: {{ include "solar.apiserver.serviceName" . }}
  groupPriorityMinimum: {{ .Values.apiserver.apiservice.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.apiservice.versionPriority }}
{{- end }}
