{{- if and .Values.apiserver.enabled .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "solar.certManager.certificateName" . }}
  namespace: {{ include "solar.namespace" . }}
  labels:
    {{- include "solar.apiserver.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "solar.apiserver.serviceName" . }}.{{ include "solar.namespace" . }}.svc
    - {{ include "solar.apiserver.serviceName" . }}.{{ include "solar.namespace" . }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.certManager.issuer.kind }}
    name: {{ include "solar.certManager.issuerName" . }}
  secretName: {{ include "solar.certManager.certificateSecretName" . }}
  duration: {{ .Values.certManager.certificate.duration }}
  renewBefore: {{ .Values.certManager.certificate.renewBefore }}
{{- end }}
