# FIXME: move this file to an appropriate location
release:
  chart:
    name: test-release
    description: Test Release Chart
    version: v1.0.0
    appVersion: v1.0.0
  input:
    component:
      name: test-component
    helm:
      repository: oci://example.com/helm
      tag: v1.0.0
    kro:
      repository: oci://example.com/kro
      tag: v1.0.0
    resources:
      resource1:
        repository: oci://example.com/resource1
        tag: v1.0.0
  values: {}
