{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "solar.namespace" . }}
  labels:
    {{- include "solar.labels" . | nindent 4 }}
    app.kubernetes.io/component: namespace
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
