name: Golang CI
permissions:
  contents: read

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "docs/**"
      - "**/*.md"

env:
  GO_MODULE: https://github.com/opendefensecloud/solution-arsenal
  GO_VERSION: 1.25.7

jobs:
  lint:
    runs-on: arc-scale-set
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: lint-license-and-shell
        run: |
          make lint-no-golangci
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9

  test:
    needs: lint
    runs-on: arc-scale-set
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: test
        run: |
          make ocm
          make ocm-transfer-helmdemo
          make test
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.2.0
        with:
          infile: solar.coverprofile
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.3.7
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov
